# Generated by Django 4.2.16 on 2025-06-16 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('acquisition_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('condition', models.CharField(default='New', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('assigned', 'Assigned'), ('maintenance', 'Maintenance'), ('disposed', 'Disposed')], default='active', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
